smile/homepage/urls.py
from django.urls import path
from . import views

app_name = "homepage"

urlpatterns = [
    path('', views.home, name="home")
]

smile/login/urls.py
from django.urls import path
from . import views

app_name = "smilelogin"

urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

smile/registration/urls.py
from django.urls import path
from . import views

app_name = "login"

urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

smile/signup/urls.py
from django.urls import path
from . import views

app_name = "signup"

urlpatterns = [
    path('', views.signup, name='signup'),
    path('activate/<uidb64>/<token>', views.activate, name='activate')
]

smile/smile/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

app_name = 'smile'

urlpatterns = [
    path('', include('homepage.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('accounts/login/', include('registration.urls')),
    path('accounts/register/', include('signup.urls', namespace='signup')),
    path('accounts/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    admin_url = 'admin/'
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    admin_url = 'smileadmin/'
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]


urlpatterns += [
    path(admin_url, admin.site.urls)
]

smile/templates/base.html
{% include 'header.html' %}

{% block content %}

{% endblock %}

{% include 'footer.html' %}

smile/templates/footer.html
{% load static %}

    <script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
    <script src="{% static 'js/toastr.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

smile/templates/header.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Smile Game</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/toastr.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-light">
        <div class="container">
            <a class="navbar-brand text-light" href="{% url 'homepage:home' %}">Smile Game</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="navbar-nav mb-2 mb-lg-0 ">
                    
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                    <!-- <a class="nav-link text-light" href="login">Login</a> -->
                        <a class="nav-link text-light logout" href="{% url 'login:logout'%}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link  text-light active" aria-current="page" href="{% url 'signup:signup' %}">Register Here</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light login" aria-current="page" href="{% url 'login:login' %}">Login</a>
                    </li>
                    {% endif %}
                    
                </ul>
            </div>
        </div>
    </nav>