smile/login/urls.py
from django.urls import path
from . import views

app_name = "smilelogin"

urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

smile/registration/urls.py
from django.urls import path
from . import views

app_name = "login"

urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

smile/signup/urls.py
from django.urls import path
from . import views

app_name = "signup"

urlpatterns = [
    path('', views.signup, name='signup'),
    path('activate/<uidb64>/<token>', views.activate, name='activate')
]

smile/smile/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

app_name = 'smile'

urlpatterns = [
    path('', include('homepage.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('accounts/login/', include('registration.urls')),
    path('accounts/register/', include('signup.urls', namespace='signup')),
    path('accounts/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    admin_url = 'admin/'
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    admin_url = 'smileadmin/'
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]


urlpatterns += [
    path(admin_url, admin.site.urls)
]

smile/signup/models.py
from django.db import models

# Create your models here.
class Signup(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    username = models.CharField(unique=True, max_length=150)
    password1 = models.CharField(max_length=128)
    password2 = models.CharField(max_length=128)
    class Meta:
        db_table = "smile"

smile/signup/forms.py
from django import forms
from django.core import validators
from django_recaptcha.fields import ReCaptchaField

class SignupForm(forms.Form):
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)
    username = forms.CharField(max_length=150)
    email = forms.CharField(max_length=254, validators=[validators.EmailValidator(message="Invalid Email")])
    password1 = forms.CharField(max_length=128, min_length=5)
    password2 = forms.CharField(max_length=128, min_length=5)
    captcha = ReCaptchaField()

smile/signup/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User, auth
from django.contrib import messages

from .forms import SignupForm

#################################################################################
from django.contrib.auth import login, logout, authenticate, get_user_model
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage, BadHeaderError
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from .tokens import account_activation_token


def signup(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = SignupForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required

            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            username = form.cleaned_data['username']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']
            email = form.cleaned_data['email']


            if password1 == password2:
                if User.objects.filter(email=email).exists():
                    messages.info(request, 'Email already taken')
                elif User.objects.filter(username=username).exists():
                    messages.info(request, 'Username already taken')
                else:
                    try:
                        user = User.objects.create_user(username=username, password=password1, email=email, first_name=first_name, last_name=last_name)
                        
                        ################################ added
                        # user1 = form.save(commit=False)
                        user.is_active=False
                        ################################

                        user.save()

                        ################################
                        activateEmail(request, user, form.cleaned_data.get('email'))
                        ################################
                        
                        messages.success(request, 'Registration successful. Please check your email to activate your account.')
                        # messages.success(request, 'Registered')
                        
                        # redirect to a new URL:
                        # return redirect('/accounts/register/')
                        return redirect('login')
                    except Exception as e:
                        # logger.error(f'Error creating user: {e}')
                        messages.error(request, 'An error occurred during registration. Please try again.')
            else:
                messages.info(request, 'Password not matching')
            
            

        # if the form is not valid
        else:
            messages.info(request, 'form is not valid')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = SignupForm()

    return render(request, 'signup/index.html', {'form': form})


########################################################################3

def activateEmail(request, user, to_email):
    mail_subject = "Activate your user account."
    message = render_to_string("signup/template_activate_account.html", {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        "protocol": 'https' if request.is_secure() else 'http'
    })

    email = EmailMessage(mail_subject, message, to=[to_email])
    
    try:
        if email.send():
            messages.success(request, f'Dear {user}, Registered, please go to you email {to_email} inbox and click on \
                    received activation link to confirm and complete the registration. Note: Check your spam folder.')
        else:
            messages.error(request, f'Problem sending email to {to_email}, check if you typed it correctly.')
    except BadHeaderError:
        messages.error(request, 'Invalid header found.')
    except Exception as e:
        messages.error(request, f'An error occurred: {e}')
        # logger.error(f'Error sending activation email: {e}')

#################################################################################


def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        messages.success(request, "Thank you for your email confirmation. Now you can login your account.")
        return redirect('/accounts/login/')
    else:
        messages.error(request, "Activation link is invalid!")

    return redirect('/')

smile/signup/templates/signup/index.html
{% extends 'base.html' %}

{% block content %}

<section>
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <!-- <form action="signup" method="POST"> -->
                <form method="post" action="{% url 'signup:signup' %}">
                    {% csrf_token %}

                    <h3 class="form-title">Create an Account</h3>

                    <!-- <div class="b-firstname form-group"> -->
                    <div class="row">
                        <div class="form-group col">
                            <label for="" class="form-label">First Name *</label>
                            <input type="text" name="first_name" id="firstname" class="form-control" placeholder="first name" >
                        </div>
                        <div class="form-group col">
                            <label for="" class="form-label">Last Name *</label>
                            <input type="text" name="last_name" id="lastname" class="form-control" placeholder="last name" >
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col">
                            <label for="" class="form-label">Username *</label>
                            <input type="text" name="username" id="username" class="form-control" placeholder="Enter your username" >
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col">
                            <label for="" class="form-label">Email *</label>
                            <input type="text" name="email" id="email" class="form-control" placeholder="name@domain.com" >
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col">
                            <label for="" class="form-label">Password *</label>
                            <input type="password" name="password1" id="password1" class="form-control" placeholder="password" >
                        </div>
                        <div class="form-group col">
                            <label for="" class="form-label">Confirm Password *</label>
                            <input type="password" name="password2" id="password2" class="form-control" placeholder="confirm password" >
                        </div>
                        
                    </div>

                    <div class="row">
                        <div class="col">
                            <p class="text-muted d-flex">- password should be minimum 5 digits</p>
                        </div>
                    </div>

                    
                    {{ form.captcha }}
                    {{ form.captcha.errors }}

                    <button type="submit" class="btn btn-primary">Sign Up</button>

                    <!-- added for Oauth -->
                    <!-- 
                        <p class="my-0 pt-3">or</p>
                        <button class="btn btn-dark"><a class="text-light" href="{% url 'social:begin' 'google-oauth2' %}">Continue with Google</a></h5></button>
                    -->
                </form>
                        
                <hr>

                <p>Have already an account? <a href="{% url 'login:login' %}">Login here</a></p>
                
            
                {% for message in messages %}
                    <h1 class="bt-{{message.tags}}" id="msg">{{message}}</h1>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
    

{% endblock %}

smile/signup/templates/signup/template_activate_account.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

{{ protocol }}://{{ domain }}{% url 'signup:activate' uidb64=uid token=token %}
{% endautoescape %}